name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go mod download

    - name: Install Venom for integration tests
      run: curl https://github.com/ovh/venom/releases/download/v1.1.0/venom.linux-amd64 -L -o ./venom && chmod +x ./venom

    - name: Install docker-compose
      run: curl -SL https://github.com/docker/compose/releases/download/v2.29.6/docker-compose-linux-x86_64 -o ./docker-compose && chmod +x ./docker-compose

    - name: Run tests
      env:
        WORKFLOW: 1
        BUILD: 1
      run: ./run_tests.sh
