name: Embedding Model Microservice (dev)

services:
  embedding_microservice:
    build: .
    ports:
      - "8000:8000"
    command: ["fastapi", "dev", "--host", "0.0.0.0", "run.py"]
    restart: always
    volumes:
      - ./:/app

    