version: '3.8'

services:
  eigen_db:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - eigen_db:/app/eigen
    environment:
      - GIN_MODE=release
      - TEST_MODE=0
    restart: always

volumes:
  eigen_db:
