services:
  eigendb:
    image: ghcr.io/eigen-db/eigendb-base:latest
    working_dir: /src
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - .:/src
    command: 
      - moon run eigendb:build && cd apps/eigendb && ./dist/eigen_db

volumes:
  eigendb_data: