version: '3.8'

services:
  eigen_db:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - GIN_MODE=release
      - TEST_MODE=1
    depends_on: 
     - redis
    restart: always

  redis:
    image: redis:latest
    ports: 
      - "127.0.0.1:6379:6379"
    restart: always
