version: '3.8'

services:
  eigen_db:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - eigen_db:/app/eigen
    environment:
      - REDIS_HOST=redis
      - GIN_MODE=release
    depends_on: 
     - redis
    restart: always

  redis:
    image: redis:latest
    ports: 
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: always


volumes:
  eigen_db:
  redis_data:
