services:
  eigen_db:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - eigen_db:/app/eigen
    environment:
      - GIN_MODE=release
      - E2E_TEST_MODE=0
    command: ["/bin/bash", "-c", "/app/eigen_db"]
    restart: always

volumes:
  eigen_db:
