# ISSUE: Interactive config menu doesn't work when running eigendb using docker compose. Menu works when running eigendb using the Dockerfile. 

services:
  eigen_db:
    build:
      context: ../../
      dockerfile: Dockerfile.eigendb
    ports:
      - "8080:8080"
    volumes:
      - eigen_db:/app/apps/eigendb/eigen
    environment:
      - E2E_TEST_MODE=0
    restart: always

volumes:
  eigen_db:
