name: Update Config Test Suite

vars:
  url: http://localhost:8080

testcases:
- name: Update API address (successful)
  steps:
  - type: http
    method: POST
    url: "{{.url}}/update-config/api/address"
    body: > 
      {"updatedAddress": "127.0.0.1"}
    headers:
      X-Eigen-API-Key: test
    timeout: 5
    assertions:
    - result.statuscode ShouldEqual 200
    - result.bodyjson.message ShouldEqual "API address updated. Please restart the database for it to take effect."
    - result.bodyjson.status ShouldEqual 200

- name: Update API address (unsuccessful)
  steps:
  - type: http
    method: POST
    url: "{{.url}}/update-config/api/address"
    body: > 
      {"updatedAddress": 1}
    headers:
      X-Eigen-API-Key: test
    timeout: 5
    assertions:
    - result.statuscode ShouldEqual 400
    - result.bodyjson.message ShouldEqual "Bad request"
    - result.bodyjson.status ShouldEqual 400
    - result.bodyjson.error.code ShouldEqual INVALID_REQUEST_BODY
    - result.bodyjson.error.description ShouldEqual "The body you provided in your request is invalid."

- name: Update API port (successful)
  steps:
  - type: http
    method: POST
    url: "{{.url}}/update-config/api/port"
    body: > 
      {"updatedPort": 5000}
    headers:
      X-Eigen-API-Key: test
    timeout: 5
    assertions:
    - result.statuscode ShouldEqual 200
    - result.bodyjson.message ShouldEqual "API port updated. Please restart the database for it to take effect."
    - result.bodyjson.status ShouldEqual 200

- name: Update API port (unsuccessful)
  steps:
  - type: http
    method: POST
    url: "{{.url}}/update-config/api/port"
    body: > 
      {"updatedPort": "hi"}
    headers:
      X-Eigen-API-Key: test
    timeout: 5
    assertions:
    - result.statuscode ShouldEqual 400
    - result.bodyjson.message ShouldEqual "Bad request"
    - result.bodyjson.status ShouldEqual 400
    - result.bodyjson.error.code ShouldEqual INVALID_REQUEST_BODY
    - result.bodyjson.error.description ShouldEqual "The body you provided in your request is invalid."

# - name: Update HNSW Similarity Metric (successful)
#   steps:
#   - type: http
#     method: POST
#     url: "{{.url}}/update-config/hnsw-params/similarity-metric"
#     body: > 
#       {"updatedMetric": "cosine"}
#     headers:
#       X-Eigen-API-Key: test
#     timeout: 5
#     assertions:
#     - result.statuscode ShouldEqual 200
#     - result.bodyjson.message ShouldEqual "Vector similarity metric updated. Please restart the database for it to take effect."
#     - result.bodyjson.status ShouldEqual 200

# - name: Update HNSW Similarity Metric (unsuccessful)
#   steps:
#   - type: http
#     method: POST
#     url: "{{.url}}/update-config/hnsw-params/similarity-metric"
#     body: > 
#       {"updatedMetric": 1}
#     headers:
#       X-Eigen-API-Key: test
#     timeout: 5
#     assertions:
#     - result.statuscode ShouldEqual 400
#     - result.bodyjson.message ShouldEqual "Bad request"
#     - result.bodyjson.status ShouldEqual 400
#     - result.bodyjson.error.code ShouldEqual INVALID_REQUEST_BODY
#     - result.bodyjson.error.description ShouldEqual "The body you provided in your request is invalid."

# - name: Update HNSW Similarity Metric (invalid)
#   steps:
#   - type: http
#     method: POST
#     url: "{{.url}}/update-config/hnsw-params/similarity-metric"
#     body: > 
#       {"updatedMetric": "hello"}
#     headers:
#       X-Eigen-API-Key: test
#     timeout: 5
#     assertions:
#     - result.statuscode ShouldEqual 400
#     - result.bodyjson.message ShouldEqual "Something went wrong when trying to update the similarity metric."
#     - result.bodyjson.status ShouldEqual 400
#     - result.bodyjson.error.code ShouldEqual INVALID_SIMILARITY_METRIC
#     - result.bodyjson.error.description ShouldEqual "invalid similarity metric"
