apiVersion: v1
kind: Service
metadata:
  name: eigen-{{ .Values.customerId }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: eigen-{{ .Values.customerId }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
