apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eigeninfra-controller-clusterrole
rules:
  - apiGroups: [""]
    resources: ["secrets", "services", "configmaps", "namespaces"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "update", "delete"]
