apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eigeninfra-controller-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ctl.eigeninfra.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eigeninfra-controller-svc
                port:
                  number: 80
