apiVersion: v1
kind: Service
metadata:
  name: eigeninfra-controller-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: eigeninfra-controller-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
