name: 'CI'
on: 
  push:
jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: Login to GHCR & pull base image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ghcr.io/eigen-db/eigendb-base:latest

      - name: Run `moon ci` in base image
        run: |
          docker run -v ${{ github.workspace }}:/src ghcr.io/eigen-db/eigendb-base:latest "su ci_user -c \"bash -i -c 'moon ci'\""

      - name: Linter (apps/eigendb)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: apps/eigendb
          args: --timeout=3m

      - name: Linter (apps/controller)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: apps/controller
          args: --timeout=3m

      - name: Linter (libs/hnswgo)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: libs/hnswgo
          args: --timeout=3m
      
      - name: Linter (libs/faissgo)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: libs/faissgo
          args: --timeout=3m

      # - uses: 'moonrepo/setup-toolchain@v0'
      # - run: 'moon ci'