name: 'CI'
on: 
  push:
jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
          submodules: 'true'
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull base image
        run: docker pull ghcr.io/eigen-db/eigendb-base:latest

      - name: Run `moon ci` in base image
        run: docker run -v ${{ github.workspace }}:/src ghcr.io/eigen-db/eigendb-base:latest "chown -R ci_user:ci_user /src && cd /src && su ci_user -c \"bash -c 'moon ci'\""
