name: 'CI'
on: 
  push:
jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Linter (apps/eigendb)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: apps/eigendb
          args: --timeout=3m

      - name: Linter (apps/controller)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: apps/controller
          args: --timeout=3m

      - name: Linter (libs/hnswgo)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: libs/hnswgo
          args: --timeout=3m

      - uses: 'moonrepo/setup-toolchain@v0'
      - run: 'moon ci'